http_server:
  addresses: ""
  port: "8080"
  read_timeout: 60s
  write_timeout: 60s
  read_header_timeout: 60s
  shutdown_timeout: 60s

database:
  type: mongodb
  mongo:
    address: "dating1:012345678@cluster0.sudw4.mongodb.net/dating?retryWrites=true&w=majority"
    timeout: 15s
    username: ""
    password: ""
    database: "dating"
    
cloudinary:
  url: ""

jwt:
  duration: 24h
mail:
  email: ""
  password: ""
  smtp:
    host_mail: "smtp.gmail.com"
    port_mail: "587"
  confirm_timeout: 120s
  src_template: "internal/pkg/mail/template/index.html"
